# Generated by Django 5.2.3 on 2025-07-01 02:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[("UPCOMING", "Upcoming"), ("COMPLETED", "Completed")],
                default="UPCOMING",
                max_length=20,
            ),
        ),
    ]
