# Generated by Django 5.2.3 on 2025-07-10 07:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_event_status"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Participant",
        ),
    ]
