# Generated by Django 5.2.3 on 2025-07-10 10:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0004_event_participants"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="participants",
            new_name="rsvped_users",
        ),
    ]
