# Generated by Django 5.2.3 on 2025-07-10 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0005_rename_participants_event_rsvped_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="event_image",
            field=models.ImageField(blank=True, null=True, upload_to="Event_Image"),
        ),
    ]
